### PR TITLE
Update the default unidocGenjavadocVersion to 0.18

### PR DESCRIPTION
**Pull request by ksen0byte**
Related to: https://github.com/sbt/sbt-unidoc/issues/110

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]

**Comment by ksen0byte** [comment]
Do I need to do anything else to get it merged?
@SethTisue

**Comment by SethTisue** [comment]
@pikinier20 are you still around and doing releases and such...?

**Comment by pikinier20** [comment]
Hey, yes, do we need to have separate release after merging that?

**Comment by SethTisue** [comment]
(I know next to nothing about this plugin. Maybe @eed3si9n will answer.)

**Comment by eed3si9n** [comment]
If sbt-unidoc no longer works for latest Scala 2.12.x, releasing a new version sounds good.

**Review by eed3si9n — APPROVED** [review]
Thanks

**Pull request merged**
